language: node_js
node_js:
  - '6'
install:
  - npm install
script:
  - npm test
  - npm run lint
  # Also perform a sanity check on the CLI
  - npm start -- -i demo.ccsb -o demo.svg --title "Cash Out"
  - diff demo.svg test/cases/cash.svg
  - rm demo.svg
deploy:
  provider: npm
  email: shane@sffc.xyz
  api_key:
    secure: shHe6NvSI6YznJBjVLCbISbVR1fuzBgKnwpxdG3/vihvd1gNwEDgjsiX8kNGf3QwiQ6apUa8oZbx31XdEXX8puE9oeOkLhK+bT+woYljMVnpS+PGuZv2XGCcaH8FuERZorYwKOc92fHHLEj1iyRLzy0qp6GgYNKKDFwChSsXALxxMFg4SEE7Oqq1fm2J3NBt9Y+SGD4bUNS/xIioexKY5P4sGW0XLvajbjV/rOu5FYbtzR4VirUu79FnEwugh6plQR3TgmB+DFKfb4SVhwjgAIK6m0RDOUMzRgiUsgt2mu3MTCucFPRpkXLsbn2I7Jg5UFfSiwtgMQ1GN+q2u1vqrr8PcM6qICw5ZjW04IV5AyBJtwIl5HtzFy7fQuvYXGQ8gVo/lJHbyQSjPTL+XmVrNpxjx6dcuOqLLtZOK4EtEa72zD0fMJxSMK3Hmtwc4yEpW2jUu2/4yvzTYm7ZaPeYX6/HKHs89nx6TP9w2C078T7x4GwdGDwDlHB4d69RL7hrw6eCk2SF48uVgsHECqflod1qP97ZDnmLt+ONfQaLcUVueCPrPFjn/LeYwNLsrsNP1Fbq3nzml6wfNxUlGt3Vmnq/GDQWDiLj9KD8wExcD2c1oiTVh9vAZxXh6kkeGhmB00TUQS/tI9E7nB9RWmI/VuhIeMikNGPtusK99fIbtLU=
  on:
    tags: true
    repo: sffc/card-creatr
